# Generated by Django 3.0.5 on 2020-07-11 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_1', models.CharField(max_length=200)),
                ('Address_2', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(choices=[('maharashtra', 'maharashtra'), ('gujrat', 'gujrat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab')], max_length=20)),
                ('zipCode', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingaddress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'billingaddress',
                'verbose_name_plural': 'billingaddresss',
            },
        ),
    ]
