# Generated by Django 3.0.5 on 2020-07-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='Address_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
