# Generated by Django 3.0.8 on 2020-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
