# Generated by Django 3.0.8 on 2020-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
